; ZXA player v0.2
; by Arda Erdikmen
; Plays ZXA files generated by ZX Animator.
; Compile this file for every new ZXA.
; Example:
; pasmo -v --tapbas zxa-animator128.asm animation_out.tap

; Creative Commons Attribution-NonCommercial 4.0 International Public License
; https://creativecommons.org/licenses/by-nc/4.0/legalcode

; ZXA stream:
; 00..3F reserved
; 40..5A normal write: HI LO VALUE
; 5B..BF reserved
; C0..DA same-page batch: NN (LL VALUE)*NN, HI = command - 128
; DB raw run: HH LL NN DATA*NN
; DC counted loop: NN, total playback count before returning to BASIC
; DD endless loop
; DE end frame: DELAY
; DF RLE keyframe: RLE stream that expands to 6912 screen bytes
; E0..EF reserved
; F0..F7 set border color, color = command & 7
; F8..FE reserved
; FF raw keyframe: 6912 raw screen bytes

org 24576    ; #6000

Entry:
di
push af
push bc
push de
push hl
push ix
push iy
ld (SaveRegSP),sp
jp MainCode

SaveRegSP      DEFW 0
startofframes  DEFW 0
loopcounter    DEFB 0

; Play frames from the ZXA stream.

MainCode:

; Set up IM 2.
; The interrupt service routine contains only RET.
; HALT resumes immediately after the interrupt.

di
ld hl,65021             ; Place a single RET instruction at this address.
ld (hl),201             ; 201 = RET
ld   hl,65024           ; Fill this RAM area for the interrupt vector table.
ld   de,65025
ld   (hl),253           ; 253 = FD
ld   b,e                ; E = #01, so BC = #0101 = 257.
ld   c,e
ldir                    ; Fill 257 bytes with FD so any vector offset points to FDFD.

ld   a,254              ; High byte for the interrupt vector table.
ld   i,a                ; 254 avoids ULA snow and works on all models.
im   2

; Interrupt setup complete.

xor a
ld (loopcounter),a
out (254),a             ; Black border.

ld hl,START
ld (startofframes),hl   ; Stream start address used for looping.
jp writeBytes

mainloop:
ei
halt
di

writeBytes:
ld a,(hl)               ; 40..5A=normal write, C0..DA=batch, DB..DE=commands.
cp 64
jp c,badCommand         ; 00..3F reserved.
cp 91
jp c,writeByte          ; 40..5A normal HI LO VALUE.
cp 192
jp c,badCommand         ; 5B..BF reserved.
cp 219
jp c,samePageBatch      ; C0..DA same-page batch.
jp z,rawRun             ; DB raw run.
cp 220
jp z,counterLoop        ; DC counted loop.
cp 221
jp z,loopanim           ; DD endless loop.
cp 222
jp z,nextframe          ; DE end frame.
cp 223
jp z,rleKeyFrame        ; DF RLE keyframe.
cp 240
jp c,badCommand         ; E0..EF reserved.
cp 248
jp c,setBorder          ; F0..F7 set border color.
cp 255
jp z,rawKeyFrame        ; FF raw keyframe.
jp badCommand           ; F8..FE reserved.

writeByte:
ld d,a
inc hl
ld e,(hl)               ; Low byte of target address.
inc hl
ld a,(hl)               ; Data byte.
ld (de),a               ; Write to screen memory.
inc hl                  ; Move to next stream item.
jp writeBytes

samePageBatch:
sub 128                 ; C0..DA -> 40..5A address high byte.
ld d,a
inc hl
ld b,(hl)               ; NN
inc hl
ld a,b
or a
jp z,writeBytes         ; NN=0 is a no-op.

samePageLoop:
ld e,(hl)               ; LL
inc hl
ld a,(hl)               ; VALUE
ld (de),a
inc hl
djnz samePageLoop
jp writeBytes

rawRun:
inc hl
ld d,(hl)               ; HH
inc hl
ld e,(hl)               ; LL
inc hl
ld b,(hl)               ; NN
inc hl
ld a,b
or a
jp z,writeBytes         ; NN=0 is a no-op.

rawRunLoop:
ld a,(hl)
ld (de),a
inc hl
inc de
djnz rawRunLoop
jp writeBytes

counterLoop:
inc hl
ld b,(hl)               ; NN total playback count.
inc hl
ld a,(loopcounter)
or a
jp nz,counterActive
ld a,b
or a
jp z,Recover            ; NN=0 exits immediately.

counterActive:
dec a
ld (loopcounter),a
jp z,Recover
ld hl,(startofframes)
jp writeBytes

nextframe:
inc hl
ld b,(hl)               ; DE DELAY
inc hl
xor a
cp b
jp z,mainloop           ; DELAY=0 means no extra wait.

waitloop:
ei
halt                    ; Wait one interrupt.
dec b
jp nz,waitloop
jp mainloop

loopanim:
ld hl,(startofframes)
jp writeBytes

setBorder:
and 7
out (254),a
inc hl
jp writeBytes

rawKeyFrame:
inc hl
ld de,16384
ld bc,6912
ldir
jp writeBytes

rleKeyFrame:
inc hl
ld de,16384

rleKeyFrameLoop:
ld a,(hl)
inc hl
bit 7,a
jp nz,rleRepeatRun
inc a
ld b,0
ld c,a
ldir
jp checkKeyFrameEnd

rleRepeatRun:
and 127
inc a
ld b,a
ld a,(hl)
inc hl

rleRepeatLoop:
ld (de),a
inc de
djnz rleRepeatLoop

checkKeyFrameEnd:
ld a,d
cp 91
jp nz,rleKeyFrameLoop
jp writeBytes

badCommand:
ld a,2
out (254),a             ; Red border indicates invalid stream data.
di
halt

Recover:
di
ld sp,(SaveRegSP)
pop iy
pop ix
pop hl
pop de
pop bc
pop af
im 1
ei
ret

START:

incbin "01.zxa"

end 24576
